version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./api
      target: development
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    env_file:
      - .env
    command: npm run start
    depends_on:
      - postgres

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert.key:/root/ssl/cert.key
      - ./nginx/cert.pem:/root/ssl/cert.pem
    ports:
      - "443:443"
    depends_on:
      - api

  postgres:
    image: postgres:14.2
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  dbdata:
